platform :ios, '6.0'

target :ARAnalyticsBootstrapMac do
  pod 'ARAnalytics/KISSmetricsMac', :path => "../"
end

target :ARAnalyticsBootstrapiOS do
  pod 'ARAnalytics/KISSmetrics', :path => "../"
end

