source 'https://github.com/CocoaPods/Specs.git'

target :ARAnalyticsBootstrapiOS do
  platform :ios, '7.0'
  
  pod 'ARAnalytics/Intercom', :path => "../"
  pod 'ARAnalytics/DSL', :path => "../"
end

target "ARAnalyticsiOSTests" do
  pod 'Specta', '~> 0.2'
  pod 'Expecta', '~> 0.2'
  pod 'OCMock', '2.2.4'
end
