target :ARAnalyticsBootstrapMac do
  platform :osx, '10.7'
#  pod "Mixpanel-OSX-Community", :path => "../../Mixpanel-OSX-Community/"
  pod "Mixpanel-OSX-Community", :git => "https://github.com/orta/mixpanel-osx-unofficial"

  pod 'ARAnalytics/KISSmetricsOSX', :path => "../"
#  pod 'ARAnalytics/CountlyOSX', :path => "../"
end

target :ARAnalyticsBootstrapiOS do
  platform :ios, '6.0'
  pod 'ARAnalytics/TestFlight', :path => "../"     
  pod "ARAnalytics/Mixpanel"        
  pod "ARAnalytics/Localytics"      
  pod "ARAnalytics/Flurry"          
  pod "ARAnalytics/GoogleAnalytics" 
  pod "ARAnalytics/KISSmetrics"     
  pod "ARAnalytics/Crittercism"     
  pod "ARAnalytics/Countly"         
  pod "ARAnalytics/Bugsnag"         
  pod "ARAnalytics/Helpshift"       
  pod "ARAnalytics/Crashlytics"
  pod "ARAnalytics/Tapstream"
  pod 'ARAnalytics/NewRelic', :path => "../"     
end

