target :ARAnalyticsBootstrapMac do
  platform :osx, '10.7'
  pod 'ARAnalytics/KISSmetricsMac', :path => "../"
end

target :ARAnalyticsBootstrapiOS do
  platform :ios, '6.0'
  pod 'ARAnalytics/TestFlight', :path => "../"
end

