#target :ARAnalyticsBootstrapMac do
#  platform :osx, '10.7'
#  pod "Mixpanel-OSX-Community", :path => "../../Mixpanel-OSX-Community/"
#  pod "Mixpanel-OSX-Community", :git => "https://github.com/orta/mixpanel-osx-unofficial"

#  pod 'ARAnalytics/KISSmetricsOSX', :path => "../"
#  pod 'ARAnalytics/CountlyOSX', :path => "../"
# end

target :ARAnalyticsBootstrapiOS do
  platform :ios, '6.0'
  
  # think 3.5.5 / 3.5.6 are broken
  pod 'HockeySDK', '3.5.4'
  
  pod 'ARAnalytics', :path => "../"
  pod 'ARAnalytics/DSL', :path => "../"
end

target "ARAnalyticsiOSTests" do
  pod 'Specta', '~> 0.2'
  pod 'Expecta', '~> 0.2'
  pod 'OCMock', '2.2.4'
end
